project_id = "swrolhjwcumynnjkugbu"
[functions.order-notifier]
enabled = true
verify_jwt = true
import_map = "./functions/order-notifier/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/order-notifier/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/order-notifier/*.html" ]

[functions.test-telegram-notification]
enabled = true
verify_jwt = true
import_map = "./functions/test-telegram-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/test-telegram-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/test-telegram-notification/*.html" ]

[functions.telegram-bot-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/telegram-bot-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/telegram-bot-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/telegram-bot-webhook/*.html" ]
